<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,600&display=swap" rel="stylesheet"/>

    <!-- Styles -->
    <style>
        table, th, td {
            border: 1px solid;
        }
    </style>
</head>
<body class="antialiased">
<table>
    <tbody>
    <tr>
        <th></th>
        <th></th>
        <th>Poids</th>
        <th>adulte</th>
        <th></th>
    </tr>
    <tr>
        <td></td>
        <td>11kg</td>
        <td></td>
        <td>12kg</td>
        <td></td>
    </tr>
    <tr>
        <td>âge du chiot (mois)</td>
        <td>grammes</td>
        <td>dose(s)</td>
        <td>grammes</td>
        <
        td>dose(s)</td></tr>
    <tr>
        <td>6</td>
        <td>223</td>
        <td>3</td>
        <td>223</td>
        <td>3</td>
    </tr>
    <tr>
        <td>7</td>
        <td>202</td>
        <td>2+6/8</td>
        <td>202</td>
        <td>2+6/8</td>
    </tr>
    <tr>
        <td>8</td>
        <td>181</td>
        <td>2+4/8</td>
        <td>181</td>
        <td>2+4/8</td>
        </t
        r>
    <tr>
        <td>9</td>
        <td>161</td>
        <td>2+1/8</td>
        <td>161</td>
        <td>2+1/8</td>
    </tr>
    <tr>
        <td>10</td>
        <td>160</td>
        <td>1+6/8</td>
        <td>160</td>
        <td>1+6/8</td>
    </tr>
    <tr>
        <td>11</td>
        <td>158</td>
        <td>1+6/8</td>
        <td>158</td>
        <td>1+6/8</td>
    </tr>
    <tr>
        <t
            d>12</td>
            <td>161</td>
            <td>2+1/8</td>
            <td>161</td>
            <td>2+1/8</td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td>15kg</td>
        <td></td>
        <td>20kg</td>
        <td></td>
    </tr>
    <tr>
        <td>âge du chiot (mois)</td>
        <td>gramm
            es
        </td>
        <td>dose(s)</td>
        <td>grammes</td>
        <td>dose(s)</td>
    </tr>
    <tr>
        <td>6</td>
        <td>265</td>
        <td>3+5/8</td>
        <td>329</td>
        <td>4+4/8</td>
    </tr>
    <tr>
        <td>7</td>
        <td>246</td>
        <td>3+3/8</td>
        <td>306</td>
        <td>4+1/8</td>
    </tr>
    <tr>
        <td>8</td>
        <td>229
        </td>
        <td>3+1/8</td>
        <td>285</td>
        <td>3+7/8</td>
    </tr>
    <tr>
        <td>9</td>
        <td>209</td>
        <td>2+7/8</td>
        <td>261</td>
        <td>3+4/8</td>
    </tr>
    <tr>
        <td>10</td>
        <td>190</td>
        <td>2+5/8</td>
        <td>237</td>
        <td>3+2/8</td>
    </tr>
    <tr>
        <td>11</td>
        <td>188</td>
        <td
        >2+4/8
        </td>
        <td>234</td>
        <td>3+1/8</td>
    </tr>
    <tr>
        <td>12</td>
        <td>187</td>
        <td>2+4/8</td>
        <td>233</td>
        <td>3+1/8</td>
    </tr>
    <tbody>
</table>
<table>
    <tbody>
    <tr>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    <tr>
        <td></td>
        <td>13kg</td>
        <td></td>
    </tr>
    <tr>
        <td>âge du chiot (mois)</td>
        <td>grammes</td>
        <td>dose(s)</td>
    </tr>
    <tr>
        <td>6</td>
        <td>251</td>
        <td>3</td>
    </tr>
    <tr>
        <td>7</td>
        <td>233</td>
        <td>2+6/8</td>
    </tr>
    <tr>
        <td>8</td>
        <td>217</td>
        <td>2+4/8</td>
    </tr>
    <tr>
        <td>9</td>
        <td>198</td>
        <
        td>2+1/8</td></tr>
    <tr>
        <td>10</td>
        <td>180</td>
        <td>2+1/8</td>
    </tr>
    <tr>
        <td>11</td>
        <td>178</td>
        <td>2+1/8</td>
    </tr>
    <tr>
        <td>12</td>
        <td>198</td>
        <td>2+1/8</td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td>25kg</td>
        <td><
            /td>
    </tr>
    <tr>
        <td>âge du chiot (mois)</td>
        <td>grammes</td>
        <td>dose(s)</td>
    </tr>
    <tr>
        <td>6</td>
        <td>389</td>
        <td>5+2/8</td>
    </tr>
    <tr>
        <td>7</td>
        <td>387</td>
        <td>5+2/8</td>
    </tr>
    <tr>
        <td>8</td>
        <td>351</td>
        <td>4+6/8</td>
    </tr>
    <tr>
        <td>9<
            /td>
        <td>315</td>
        <td>4+2/8</td>
    </tr>
    <tr>
        <td>10</td>
        <td>281</td>
        <td>3+6/8</td>
    </tr>
    <tr>
        <td>11</td>
        <td>279</td>
        <td>3+6/8</td>
    </tr>
    <tr>
        <td>12</td>
        <td>277</td>
        <td>3+6/8</td>
    </tr>
    <tbody>
</table>
</body>
</html>
